name: brg_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_offline: ^4.0.0
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
